_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.10
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
activation:
    value: tanh
batch_size:
    value: 32
beta:
    value: 0.5
beta1:
    value: 0.9
beta2:
    value: 0.999
dataset:
    value: fashion_mnist
epochs:
    value: 10
epsilon:
    value: 1e-08
hidden_layers:
    value:
        - 128
        - 128
hidden_layers_str:
    value: 128,128
hidden_size:
    value: 4
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
momentum:
    value: 0.5
num_layers:
    value: 2
optimizer:
    value: adam
val_split:
    value: 0.1
wandb_entity:
    value: da24m008-iit-madras
wandb_project:
    value: mlops
weight_decay:
    value: 0.005
weight_init:
    value: xavier
