_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.10
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
activation:
    value: sigmoid
batch_size:
    value: 4
beta:
    value: 0.5
beta1:
    value: 0.5
beta2:
    value: 0.5
dataset:
    value: fashion_mnist
epochs:
    value: 1
epsilon:
    value: 1e-06
hidden_layers:
    value:
        - 4
hidden_layers_str:
    value: "4"
hidden_size:
    value: 4
learning_rate:
    value: 0.1
loss:
    value: cross_entropy
loss_type:
    value: compare
momentum:
    value: 0.5
num_layers:
    value: 1
optimizer:
    value: sgd
val_split:
    value: 0.1
wandb_entity:
    value: da24m008-iit-madras
wandb_project:
    value: mlops
weight_decay:
    value: 0
weight_init:
    value: random
