wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
beta:
  value: 0.95
beta1:
  value: 0.9
beta2:
  value: 0.999
dataset:
  value: mnist
epochs:
  value: 15
epsilon:
  value: 1.0e-08
hidden_size:
  value: 128,64,32
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
momentum:
  value: 0
num_layers:
  value: 3
optimizer:
  value: adam
val_split:
  value: 0.1
weight_decay:
  value: 0.0001
weight_init:
  value: xavier
