_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.7
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
activation:
    value: tanh
batch_size:
    value: 32
beta:
    value: 0.99
beta1:
    value: 0.95
beta2:
    value: 0.9999
dataset:
    value: mnist
epochs:
    value: 15
epsilon:
    value: 1e-08
hidden_size:
    value: 128,64,32
learning_rate:
    value: 0.0001
loss:
    value: mean_squared_error
momentum:
    value: 0.5
num_layers:
    value: 3
optimizer:
    value: nag
val_split:
    value: 0.1
weight_decay:
    value: 0.0001
weight_init:
    value: xavier
