_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.7
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
activation:
    value: tanh
batch_size:
    value: 16
beta:
    value: 0.95
beta1:
    value: 0.9
beta2:
    value: 0.9999
dataset:
    value: mnist
epochs:
    value: 15
epsilon:
    value: 1e-08
hidden_layers:
    value:
        - 32
        - 16
hidden_layers_str:
    value: 32,16
hidden_size:
    value: 32,16
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
loss_type:
    value: cross_entropy
momentum:
    value: 0.9
num_layers:
    value: 2
optimizer:
    value: momentum
val_split:
    value: 0.1
wandb_entity:
    value: shivam20102-iiit
wandb_project:
    value: DA6401_Assignment1_new14
weight_decay:
    value: 0
weight_init:
    value: xavier
