wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
beta:
  value: 0.95
beta1:
  value: 0.95
beta2:
  value: 0.9999
dataset:
  value: mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_size:
  value: '64'
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
momentum:
  value: 0.9
num_layers:
  value: 4
optimizer:
  value: rmsprop
val_split:
  value: 0.1
weight_decay:
  value: 0.01
weight_init:
  value: xavier
