_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.7
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
activation:
    value: sigmoid
batch_size:
    value: 16
beta:
    value: 0.95
beta1:
    value: 0.95
beta2:
    value: 0.9999
dataset:
    value: fashion_mnist
epochs:
    value: 5
epsilon:
    value: 1e-08
hidden_layers:
    value:
        - 128
        - 128
        - 128
        - 128
        - 128
hidden_layers_str:
    value: 128,128,128,128,128
hidden_size:
    value: "128"
learning_rate:
    value: 0.0001
loss:
    value: mean_squared_error
loss_type:
    value: mean_squared_error
momentum:
    value: 0.9
num_layers:
    value: 5
optimizer:
    value: nadam
val_split:
    value: 0.1
wandb_entity:
    value: shivam20102-iiit
wandb_project:
    value: DA6401_Assignment1_new15
weight_decay:
    value: 0.0001
weight_init:
    value: xavier
