wandb_version: 1

activation:
  value: identity
batch_size:
  value: 32
beta:
  value: 0.99
beta1:
  value: 0.9
beta2:
  value: 0.999
dataset:
  value: fashion_mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_size:
  value: 128,64,32
learning_rate:
  value: 0.1
loss:
  value: cross_entropy
momentum:
  value: 0.9
num_layers:
  value: 5
optimizer:
  value: sgd
val_split:
  value: 0.1
weight_decay:
  value: 0.01
weight_init:
  value: random
