wandb_version: 1

activation:
  value: identity
batch_size:
  value: 32
beta:
  value: 0.99
beta1:
  value: 0.9
beta2:
  value: 0.9999
dataset:
  value: fashion_mnist
epochs:
  value: 15
epsilon:
  value: 1.0e-08
hidden_size:
  value: 32,16
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
momentum:
  value: 0.5
num_layers:
  value: 2
optimizer:
  value: nag
val_split:
  value: 0.1
weight_decay:
  value: 0.0001
weight_init:
  value: random
