wandb_version: 1

activation:
  value: identity
batch_size:
  value: 128
beta:
  value: 0.99
beta1:
  value: 0.95
beta2:
  value: 0.999
dataset:
  value: fashion_mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_size:
  value: '32'
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
momentum:
  value: 0
num_layers:
  value: 3
optimizer:
  value: sgd
val_split:
  value: 0.1
weight_decay:
  value: 0.001
weight_init:
  value: xavier
