wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
beta:
  value: 0.95
beta1:
  value: 0.95
beta2:
  value: 0.999
dataset:
  value: mnist
epochs:
  value: 15
epsilon:
  value: 1.0e-08
hidden_size:
  value: 32,16
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
momentum:
  value: 0.5
num_layers:
  value: 1
optimizer:
  value: nadam
val_split:
  value: 0.1
weight_decay:
  value: 0.0001
weight_init:
  value: xavier
