wandb_version: 1

activation:
  value: identity
batch_size:
  value: 16
beta:
  value: 0.95
beta1:
  value: 0.95
beta2:
  value: 0.9999
dataset:
  value: fashion_mnist
epochs:
  value: 5
epsilon:
  value: 1.0e-08
hidden_size:
  value: 128,64,32
learning_rate:
  value: 0.1
loss:
  value: mean_squared_error
momentum:
  value: 0.9
num_layers:
  value: 4
optimizer:
  value: nag
val_split:
  value: 0.1
weight_decay:
  value: 0.0001
weight_init:
  value: random
