wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
beta:
  value: 0.99
beta1:
  value: 0.9
beta2:
  value: 0.9999
dataset:
  value: fashion_mnist
epochs:
  value: 15
epsilon:
  value: 1.0e-08
hidden_size:
  value: '32'
learning_rate:
  value: 0.1
loss:
  value: mean_squared_error
momentum:
  value: 0
num_layers:
  value: 5
optimizer:
  value: adam
val_split:
  value: 0.1
weight_decay:
  value: 0
weight_init:
  value: random
